# Generated by Django 4.0 on 2021-12-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('village', models.CharField(max_length=1000)),
                ('nin', models.CharField(max_length=1000)),
                ('cows', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
