# Generated by Django 4.0 on 2021-12-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0003_milk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milk',
        ),
    ]
