# Generated by Django 3.2 on 2021-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0005_milk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='adulteration',
            field=models.CharField(choices=[('NONE', '1'), ('LOW', '2'), ('HIGH', '3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='milk',
            name='delivery',
            field=models.CharField(choices=[('HIGHQUALITY', '1'), ('AVERAGE', '2'), ('BELOWAVERAGE', '3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='milk',
            name='smell',
            field=models.CharField(choices=[('HIGHQUALITY', '1'), ('AVERAGE', '2'), ('BELOWAVERAGE', '3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='milk',
            name='taste',
            field=models.CharField(choices=[('HIGHQUALITY', '1'), ('AVERAGE', '2'), ('BELOWAVERAGE', '3')], max_length=100),
        ),
    ]
